name: dewangga_megananda_ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.8

  # Core ML libraries
  - scikit-learn=1.3.0
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2

  # MLflow for experiment tracking
  - mlflow=2.7.1

  # Jupyter for notebooks
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipykernel=6.23.1

  # Additional utilities
  - pip=23.2.1

  # Pip packages
  - pip:
    - prometheus_client==0.17.1
    - flask==2.3.3
    - fastapi==0.103.0
    - uvicorn==0.23.2
    - python-multipart==0.0.6